loopback_users.guest = false

listeners.tcp.default = 5672
management.tcp.port = 15672
mqtt.listeners.tcp.default = 1883
mqtt.allow_anonymous = false
mqtt.vhost = /
mqtt.exchange = hvo.raw

default_vhost = /

log.console = true
log.console.level = info

vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 1GB

management.load_definitions = /etc/rabbitmq/definitions.json
