<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MQTTnet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HVO.Edge.Hosting\HVO.Edge.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HVO.Edge.HomeAssistant.Mqtt.Tests" />
  </ItemGroup>
</Project>
