resource_mode: yaml
resources:
  - url: /local/hvo/hvo-weather-wind-card.js?v=1
    type: module

dashboards:
  hvo-kasa:
    mode: yaml
    filename: hvo/dashboards/hvo-kasa.yaml
    title: HVO Power
    icon: mdi:power-plug
    show_in_sidebar: true
    require_admin: true
  hvo-energy:
    mode: yaml
    filename: hvo/dashboards/hvo-energy.yaml
    title: HVO Energy
    icon: mdi:solar-power-variant
    show_in_sidebar: true
    require_admin: true
  hvo-operations:
    mode: yaml
    filename: hvo/dashboards/hvo-operations.yaml
    title: HVO Operations
    icon: mdi:monitor-dashboard
    show_in_sidebar: true
    require_admin: true
  hvo-weather:
    mode: yaml
    filename: hvo/dashboards/hvo-weather.yaml
    title: HVO Weather
    icon: mdi:weather-windy
    show_in_sidebar: true
    require_admin: true
