namespace HVO.Hardware.DavisVantagePro2.Protocol;

/// <summary>
/// Davis Vantage Pro 2 forecast rule text strings and forecast icon bit names.
/// Rule numbers (0–195) and icon bitmask are defined in the Davis Serial
/// Communications Reference Manual Appendix A.
/// </summary>
public static class DavisForecastTable
{
    // ── Forecast icon bits ────────────────────────────────────────────────────

    private static readonly (int Bit, string Name)[] IconBits =
    [
        (0, "Rain"),
        (1, "Cloudy"),
        (2, "Partly Cloudy"),
        (3, "Sunny"),
        (4, "Snow"),
    ];

    // ── Forecast rule strings (0–195) ─────────────────────────────────────────

    private static readonly string[] Rules =
    [
        /* 000 */ "Mostly clear and cooler.",
        /* 001 */ "Mostly clear with little temperature change.",
        /* 002 */ "Mostly clear for 12 hours with little temperature change.",
        /* 003 */ "Mostly clear for 12 to 24 hours and cooler.",
        /* 004 */ "Mostly clear with little temperature change.",
        /* 005 */ "Partly cloudy and cooler.",
        /* 006 */ "Partly cloudy with little temperature change.",
        /* 007 */ "Partly cloudy with little temperature change.",
        /* 008 */ "Mostly clear and warmer.",
        /* 009 */ "Partly cloudy with little temperature change.",
        /* 010 */ "Partly cloudy with little temperature change.",
        /* 011 */ "Mostly clear with little temperature change.",
        /* 012 */ "Increasing clouds and warmer. Precipitation possible within 24 to 48 hours.",
        /* 013 */ "Partly cloudy with little temperature change.",
        /* 014 */ "Mostly clear with little temperature change.",
        /* 015 */ "Increasing clouds with little temperature change. Precipitation possible within 24 hours.",
        /* 016 */ "Mostly clear with little temperature change.",
        /* 017 */ "Partly cloudy with little temperature change.",
        /* 018 */ "Mostly clear with little temperature change.",
        /* 019 */ "Increasing clouds with little temperature change. Precipitation possible within 12 hours.",
        /* 020 */ "Mostly clear with little temperature change.",
        /* 021 */ "Partly cloudy with little temperature change.",
        /* 022 */ "Mostly clear with little temperature change.",
        /* 023 */ "Increasing clouds and warmer. Precipitation possible within 24 hours.",
        /* 024 */ "Mostly clear and warmer. Increasing winds.",
        /* 025 */ "Partly cloudy with little temperature change.",
        /* 026 */ "Mostly clear with little temperature change.",
        /* 027 */ "Increasing clouds and warmer. Precipitation possible within 12 hours. Increasing winds.",
        /* 028 */ "Mostly clear and warmer. Increasing winds.",
        /* 029 */ "Increasing clouds and warmer.",
        /* 030 */ "Partly cloudy with little temperature change.",
        /* 031 */ "Mostly clear with little temperature change.",
        /* 032 */ "Increasing clouds and warmer. Precipitation possible within 12 hours. Increasing winds.",
        /* 033 */ "Mostly clear and warmer. Increasing winds.",
        /* 034 */ "Increasing clouds and warmer.",
        /* 035 */ "Partly cloudy with little temperature change.",
        /* 036 */ "Mostly clear with little temperature change.",
        /* 037 */ "Increasing clouds and warmer. Precipitation possible within 12 hours. Increasing winds.",
        /* 038 */ "Partly cloudy with little temperature change.",
        /* 039 */ "Mostly clear with little temperature change.",
        /* 040 */ "Mostly clear and warmer. Precipitation possible within 48 hours.",
        /* 041 */ "Mostly clear and warmer.",
        /* 042 */ "Partly cloudy with little temperature change.",
        /* 043 */ "Mostly clear with little temperature change.",
        /* 044 */ "Increasing clouds with little temperature change. Precipitation possible within 24 to 48 hours.",
        /* 045 */ "Increasing clouds with little temperature change.",
        /* 046 */ "Partly cloudy with little temperature change.",
        /* 047 */ "Mostly clear with little temperature change.",
        /* 048 */ "Increasing clouds and warmer. Precipitation possible within 12 to 24 hours.",
        /* 049 */ "Mostly clear and warmer.",
        /* 050 */ "Partly cloudy with little temperature change.",
        /* 051 */ "Mostly clear with little temperature change.",
        /* 052 */ "Increasing clouds and warmer. Precipitation possible within 12 to 24 hours. Windy.",
        /* 053 */ "Partly cloudy with little temperature change.",
        /* 054 */ "Mostly clear with little temperature change.",
        /* 055 */ "Partly cloudy and cooler.",
        /* 056 */ "Partly cloudy and cooler. Possible precipitation in 24 hours.",
        /* 057 */ "Increasing clouds and cooler.",
        /* 058 */ "Mostly clear with little temperature change.",
        /* 059 */ "Partly cloudy and cooler.",
        /* 060 */ "Increasing clouds and cooler.",
        /* 061 */ "Partly cloudy with little temperature change.",
        /* 062 */ "Mostly clear with little temperature change.",
        /* 063 */ "Increasing clouds and cooler. Precipitation possible within 12 to 24 hours.",
        /* 064 */ "Mostly clear with little temperature change.",
        /* 065 */ "Increasing clouds and cooler. Precipitation possible within 12 hours.",
        /* 066 */ "Mostly clear with little temperature change.",
        /* 067 */ "Partly cloudy with little temperature change.",
        /* 068 */ "Increasing clouds and cooler.",
        /* 069 */ "Partly cloudy with little temperature change.",
        /* 070 */ "Mostly clear with little temperature change.",
        /* 071 */ "Increasing clouds and cooler. Precipitation possible within 12 hours. Windy.",
        /* 072 */ "Partly cloudy with little temperature change.",
        /* 073 */ "Mostly clear with little temperature change.",
        /* 074 */ "Increasing clouds and cooler. Precipitation possible within 12 to 24 hours. Windy.",
        /* 075 */ "Partly cloudy with little temperature change.",
        /* 076 */ "Mostly clear with little temperature change.",
        /* 077 */ "Increasing clouds and cooler. Precipitation possible within 12 to 24 hours. Windy.",
        /* 078 */ "Partly cloudy with little temperature change.",
        /* 079 */ "Mostly clear with little temperature change.",
        /* 080 */ "Rain. High winds. Turning cooler within 12 hours.",
        /* 081 */ "Rain. Possibly heavy at times. High winds. Turning cooler within 12 hours.",
        /* 082 */ "Overcast with rain. No significant temperature change.",
        /* 083 */ "Overcast with rain. No significant temperature change.",
        /* 084 */ "Rain. High winds. Little temperature change.",
        /* 085 */ "Overcast with rain. Little temperature change.",
        /* 086 */ "Rain. High winds. Little temperature change.",
        /* 087 */ "Overcast with rain. Little temperature change.",
        /* 088 */ "Overcast with rain. Warmer.",
        /* 089 */ "Overcast with rain. Warmer.",
        /* 090 */ "Rain. High winds. Turning warmer within 12 hours.",
        /* 091 */ "Rain. Possibly heavy at times. High winds. Turning warmer within 12 hours.",
        /* 092 */ "Overcast with rain. No significant temperature change.",
        /* 093 */ "Overcast with rain. No significant temperature change.",
        /* 094 */ "Rain. High winds. Little temperature change.",
        /* 095 */ "Overcast with rain. Little temperature change.",
        /* 096 */ "Rain. High winds. Little temperature change.",
        /* 097 */ "Overcast with rain. Little temperature change.",
        /* 098 */ "Rain. High winds. Turning cooler within 12 hours.",
        /* 099 */ "Rain. Possibly heavy at times. High winds. Turning cooler within 12 hours.",
        /* 100 */ "Overcast with rain. No significant temperature change.",
        /* 101 */ "Overcast with rain. No significant temperature change.",
        /* 102 */ "Rain. High winds. Little temperature change.",
        /* 103 */ "Overcast with rain. Little temperature change.",
        /* 104 */ "Rain. High winds. Little temperature change.",
        /* 105 */ "Overcast with rain. Little temperature change.",
        /* 106 */ "Overcast with rain. Warmer.",
        /* 107 */ "Overcast with rain. Warmer.",
        /* 108 */ "Overcast with rain. No significant temperature change.",
        /* 109 */ "Mostly cloudy. No significant temperature change.",
        /* 110 */ "Mostly cloudy and cooler.",
        /* 111 */ "Mostly cloudy. Little temperature change.",
        /* 112 */ "Mostly cloudy. Little temperature change.",
        /* 113 */ "Mostly cloudy. Little temperature change.",
        /* 114 */ "Mostly cloudy with little temperature change.",
        /* 115 */ "Mostly cloudy and cooler.",
        /* 116 */ "Partly cloudy with little temperature change.",
        /* 117 */ "Mostly clear with little temperature change.",
        /* 118 */ "Mostly cloudy with little temperature change. Precipitation possible in 12 to 24 hours.",
        /* 119 */ "Partly cloudy with little temperature change.",
        /* 120 */ "Mostly clear with little temperature change.",
        /* 121 */ "Mostly cloudy and cooler. Precipitation possible within 12 hours.",
        /* 122 */ "Mostly cloudy and cooler. Windy. Precipitation possible within 12 hours.",
        /* 123 */ "Mostly cloudy and cooler. Precipitation possible within 12 to 24 hours.",
        /* 124 */ "Partly cloudy with little temperature change.",
        /* 125 */ "Mostly clear with little temperature change.",
        /* 126 */ "Mostly cloudy and cooler. Precipitation possible within 24 to 48 hours.",
        /* 127 */ "Mostly cloudy with little temperature change.",
        /* 128 */ "Mostly clear with little temperature change.",
        /* 129 */ "Increasing clouds with little temperature change. Precipitation possible within 24 hours.",
        /* 130 */ "Mostly cloudy and cooler. Precipitation possible within 12 hours. Windy.",
        /* 131 */ "Partly cloudy with little temperature change.",
        /* 132 */ "Mostly clear with little temperature change.",
        /* 133 */ "Increasing clouds and cooler. Precipitation possibly heavy at times within 12 hours. Windy.",
        /* 134 */ "Partly cloudy with little temperature change.",
        /* 135 */ "Mostly clear with little temperature change.",
        /* 136 */ "Mostly cloudy and cooler. Precipitation possibly heavy at times within 24 hours.",
        /* 137 */ "Mostly cloudy and cooler.",
        /* 138 */ "Partly cloudy with little temperature change.",
        /* 139 */ "Mostly clear with little temperature change.",
        /* 140 */ "Mostly cloudy and cooler. Precipitation possibly heavy at times within 12 hours.",
        /* 141 */ "Partly cloudy with little temperature change.",
        /* 142 */ "Mostly clear with little temperature change.",
        /* 143 */ "Increasing clouds and cooler. Precipitation possibly heavy at times within 12 to 24 hours. Windy.",
        /* 144 */ "Mostly cloudy with little temperature change.",
        /* 145 */ "Partly cloudy with little temperature change.",
        /* 146 */ "Mostly clear with little temperature change.",
        /* 147 */ "Increasing clouds and cooler. Precipitation possibly heavy at times within 6 hours.",
        /* 148 */ "Mostly cloudy and cooler.",
        /* 149 */ "Partly cloudy with little temperature change.",
        /* 150 */ "Mostly clear with little temperature change.",
        /* 151 */ "Mostly cloudy and cooler. Precipitation possibly heavy at times within 6 hours. Windy.",
        /* 152 */ "Mostly cloudy and cooler.",
        /* 153 */ "Partly cloudy with little temperature change.",
        /* 154 */ "Mostly clear with little temperature change.",
        /* 155 */ "Stable and warm.",
        /* 156 */ "Warm and humid.",
        /* 157 */ "Precipitation and humid.",
        /* 158 */ "Stable. Warmer and more humid.",
        /* 159 */ "Precipitation. Warmer and more humid.",
        /* 160 */ "Precipitation. Warmer and more humid.",
        /* 161 */ "Stable. Warmer and more humid.",
        /* 162 */ "Warm and humid.",
        /* 163 */ "Precipitation and humid. Cooler.",
        /* 164 */ "Stable. Little temperature change.",
        /* 165 */ "Little temperature change. Precipitation possible in 24 hours.",
        /* 166 */ "Stable. Little temperature change.",
        /* 167 */ "Little temperature change. Precipitation possible in 12 hours.",
        /* 168 */ "Stable. Little temperature change.",
        /* 169 */ "Little temperature change. Precipitation possible in 12 hours. Windy.",
        /* 170 */ "Little temperature change. Precipitation possible in 12 to 24 hours.",
        /* 171 */ "Stable. Little temperature change.",
        /* 172 */ "Little temperature change. Precipitation possible in 12 hours. Windy.",
        /* 173 */ "Little temperature change. Precipitation possible in 12 to 24 hours. Windy.",
        /* 174 */ "Stable. Little temperature change.",
        /* 175 */ "Little temperature change. Precipitation possible in 24 to 48 hours.",
        /* 176 */ "Stable. Little temperature change.",
        /* 177 */ "Little temperature change. Precipitation possible in 12 to 24 hours. Windy.",
        /* 178 */ "Stable. Little temperature change.",
        /* 179 */ "Precipitation within 12 to 24 hours.",
        /* 180 */ "Precipitation within 12 hours. Possibly heavy at times. Windy.",
        /* 181 */ "Precipitation. Possibly heavy at times. Windy.",
        /* 182 */ "Precipitation within 12 to 24 hours. Possibly heavy at times. Windy.",
        /* 183 */ "Precipitation possibly heavy at times within 6 to 12 hours. Windy.",
        /* 184 */ "Precipitation. Possibly heavy at times. Windy.",
        /* 185 */ "Precipitation possibly heavy at times within 12 hours.",
        /* 186 */ "Precipitation possibly heavy at times within 6 to 12 hours.",
        /* 187 */ "Precipitation. Possibly heavy at times.",
        /* 188 */ "Precipitation within 24 hours.",
        /* 189 */ "Precipitation within 12 to 24 hours.",
        /* 190 */ "Precipitation within 24 to 48 hours.",
        /* 191 */ "Precipitation within 24 hours. Possibly heavy at times.",
        /* 192 */ "Precipitation within 12 to 24 hours. Possibly heavy at times.",
        /* 193 */ "Precipitation within 24 to 48 hours. Possibly heavy at times.",
        /* 194 */ "Precipitation within 12 hours. Possibly heavy at times.",
        /* 195 */ "Precipitation within 6 hours. Possibly heavy at times.",
    ];

    // ── Public API ────────────────────────────────────────────────────────────

    /// <summary>Returns the forecast text string for rule number <paramref name="rule"/> (0–195).</summary>
    public static string GetForecastString(int rule) =>
        (uint)rule < (uint)Rules.Length ? Rules[rule] : $"Unknown forecast (rule {rule})";

    /// <summary>Returns a list of active icon names from the <paramref name="icons"/> bitmask byte.</summary>
    public static IReadOnlyList<string> GetIconNames(byte icons)
    {
        var names = new List<string>(5);
        foreach (var (bit, name) in IconBits)
            if ((icons & (1 << bit)) != 0)
                names.Add(name);
        return names.AsReadOnly();
    }
}
