// <auto-generated />
using System;
using HVO.DataModels.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVO.DataModels.Migrations.V9
{
    [DbContext(typeof(HvoV9DbContext))]
    [Migration("20260427234046_InitialV9Schema")]
    partial class InitialV9Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("v9")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HVO.DataModels.Models.V9.AlertLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Acknowledged");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AlertLog", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ImageMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CameraId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("int");

                    b.Property<string>("ImageType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("CameraId", "CapturedAt");

                    b.ToTable("ImageMetadata", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.SiteConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Key");

                    b.ToTable("SiteConfiguration", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.WeatherHourly", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AvgBarometricPressureInHg")
                        .HasColumnType("float");

                    b.Property<double?>("AvgDewPointF")
                        .HasColumnType("float");

                    b.Property<double?>("AvgHumidityPercent")
                        .HasColumnType("float");

                    b.Property<double?>("AvgSolarRadiationWm2")
                        .HasColumnType("float");

                    b.Property<double?>("AvgTemperatureF")
                        .HasColumnType("float");

                    b.Property<double?>("AvgWindSpeedMph")
                        .HasColumnType("float");

                    b.Property<int?>("DominantWindDirectionDegrees")
                        .HasColumnType("int");

                    b.Property<double?>("MaxTemperatureF")
                        .HasColumnType("float");

                    b.Property<double?>("MaxUvIndex")
                        .HasColumnType("float");

                    b.Property<double?>("MaxWindGustMph")
                        .HasColumnType("float");

                    b.Property<double?>("MinTemperatureF")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("TotalRainfallInches")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart")
                        .IsUnique();

                    b.HasIndex("StationId", "PeriodStart");

                    b.ToTable("WeatherHourly", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.WeatherMinute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AvgBarometricPressureInHg")
                        .HasColumnType("float");

                    b.Property<double?>("AvgDewPointF")
                        .HasColumnType("float");

                    b.Property<double?>("AvgHumidityPercent")
                        .HasColumnType("float");

                    b.Property<double?>("AvgSolarRadiationWm2")
                        .HasColumnType("float");

                    b.Property<double?>("AvgTemperatureF")
                        .HasColumnType("float");

                    b.Property<double?>("AvgWindSpeedMph")
                        .HasColumnType("float");

                    b.Property<int?>("DominantWindDirectionDegrees")
                        .HasColumnType("int");

                    b.Property<double?>("MaxUvIndex")
                        .HasColumnType("float");

                    b.Property<double?>("MaxWindGustMph")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("TotalRainfallInches")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart")
                        .IsUnique();

                    b.HasIndex("StationId", "PeriodStart");

                    b.ToTable("WeatherMinute", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.WeatherRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("BarometricPressureInHg")
                        .HasColumnType("float");

                    b.Property<double?>("DewPointF")
                        .HasColumnType("float");

                    b.Property<double?>("HumidityPercent")
                        .HasColumnType("float");

                    b.Property<double?>("RainfallInches")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SolarRadiationWm2")
                        .HasColumnType("float");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("TemperatureF")
                        .HasColumnType("float");

                    b.Property<double?>("UvIndex")
                        .HasColumnType("float");

                    b.Property<int?>("WindDirectionDegrees")
                        .HasColumnType("int");

                    b.Property<double?>("WindGustMph")
                        .HasColumnType("float");

                    b.Property<double?>("WindSpeedMph")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("StationId", "RecordedAt");

                    b.ToTable("WeatherRaw", "v9");
                });
#pragma warning restore 612, 618
        }
    }
}
