// <auto-generated />
using System;
using HVO.DataModels.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVO.DataModels.Migrations.V9
{
    [DbContext(typeof(HvoV9DbContext))]
    partial class HvoV9DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("v9")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HVO.DataModels.Models.V9.AlertLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Acknowledged");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AlertLog", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("ApiKey", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ApiKeyClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId", "ClaimType");

                    b.ToTable("ApiKeyClaim", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ApiKeyOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("ApiKeyOwner", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsAlarm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("AlarmBitmask")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ClearedAt");

                    b.ToTable("BmsAlarm", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsCellResistance", b =>
                {
                    b.Property<long>("ReadingId")
                        .HasColumnType("bigint");

                    b.Property<byte>("CellIndex")
                        .HasColumnType("tinyint");

                    b.Property<int>("ResistanceMOhm")
                        .HasColumnType("int");

                    b.HasKey("ReadingId", "CellIndex");

                    b.ToTable("BmsCellResistance", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsCellVoltage", b =>
                {
                    b.Property<long>("ReadingId")
                        .HasColumnType("bigint");

                    b.Property<byte>("CellIndex")
                        .HasColumnType("tinyint");

                    b.Property<int>("VoltageMv")
                        .HasColumnType("int");

                    b.HasKey("ReadingId", "CellIndex");

                    b.ToTable("BmsCellVoltage", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.ToTable("BmsDevice", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsDeviceConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BalanceStartVoltageMv")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceTriggerMv")
                        .HasColumnType("bigint");

                    b.Property<bool>("BalancingEnabled")
                        .HasColumnType("bit");

                    b.Property<byte>("CellCount")
                        .HasColumnType("tinyint");

                    b.Property<long>("CellOvpMv")
                        .HasColumnType("bigint");

                    b.Property<long>("CellOvpRecoveryMv")
                        .HasColumnType("bigint");

                    b.Property<long>("CellUvpMv")
                        .HasColumnType("bigint");

                    b.Property<long>("CellUvpRecoveryMv")
                        .HasColumnType("bigint");

                    b.Property<long>("ChargeOcpDelayS")
                        .HasColumnType("bigint");

                    b.Property<long>("ChargeOcpMa")
                        .HasColumnType("bigint");

                    b.Property<long>("ChargeOcpRecoveryS")
                        .HasColumnType("bigint");

                    b.Property<double>("ChargeOtpC")
                        .HasColumnType("float");

                    b.Property<double>("ChargeOtpRecoveryC")
                        .HasColumnType("float");

                    b.Property<double>("ChargeUtpC")
                        .HasColumnType("float");

                    b.Property<double>("ChargeUtpRecoveryC")
                        .HasColumnType("float");

                    b.Property<bool>("ChargingEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<long>("DischargeOcpDelayS")
                        .HasColumnType("bigint");

                    b.Property<long>("DischargeOcpMa")
                        .HasColumnType("bigint");

                    b.Property<long>("DischargeOcpRecoveryS")
                        .HasColumnType("bigint");

                    b.Property<double>("DischargeOtpC")
                        .HasColumnType("float");

                    b.Property<double>("DischargeOtpRecoveryC")
                        .HasColumnType("float");

                    b.Property<bool>("DischargingEnabled")
                        .HasColumnType("bit");

                    b.Property<double>("MosOtpC")
                        .HasColumnType("float");

                    b.Property<double>("MosOtpRecoveryC")
                        .HasColumnType("float");

                    b.Property<long>("NominalCapacityMah")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ShortCircuitDelayUs")
                        .HasColumnType("bigint");

                    b.Property<long>("ShortCircuitRecoveryS")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "RecordedAt")
                        .IsUnique();

                    b.ToTable("BmsDeviceConfig", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsDeviceInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Firmware")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Hardware")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ManufacturingDate")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserData")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "RecordedAt")
                        .IsUnique();

                    b.ToTable("BmsDeviceInfo", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AlarmBitmask")
                        .HasColumnType("bigint");

                    b.Property<bool>("BalancingActive")
                        .HasColumnType("bit");

                    b.Property<double>("BalancingCurrentMa")
                        .HasColumnType("float");

                    b.Property<double>("BatteryTemp1C")
                        .HasColumnType("float");

                    b.Property<double>("BatteryTemp2C")
                        .HasColumnType("float");

                    b.Property<int>("CurrentMa")
                        .HasColumnType("int");

                    b.Property<long>("CycleCapacityMah")
                        .HasColumnType("bigint");

                    b.Property<long>("CycleCount")
                        .HasColumnType("bigint");

                    b.Property<int>("DeltaCellVoltageMv")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<long>("NominalCapacityMah")
                        .HasColumnType("bigint");

                    b.Property<long>("PackVoltageMv")
                        .HasColumnType("bigint");

                    b.Property<double>("PowerTubeC")
                        .HasColumnType("float");

                    b.Property<double>("PowerWatts")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("RemainingCapacityMah")
                        .HasColumnType("bigint");

                    b.Property<byte>("SocPercent")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SohPercent")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("DeviceId", "RecordedAt")
                        .IsUnique();

                    b.ToTable("BmsReading", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsReadingHourly", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AlarmCount")
                        .HasColumnType("int");

                    b.Property<int>("AvgCurrentMa")
                        .HasColumnType("int");

                    b.Property<long>("AvgPackVoltageMv")
                        .HasColumnType("bigint");

                    b.Property<double>("AvgPowerWatts")
                        .HasColumnType("float");

                    b.Property<double>("AvgSocPercent")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("MaxBatteryTemp1C")
                        .HasColumnType("float");

                    b.Property<double>("MaxBatteryTemp2C")
                        .HasColumnType("float");

                    b.Property<int>("MaxCurrentMa")
                        .HasColumnType("int");

                    b.Property<int>("MaxDeltaCellMv")
                        .HasColumnType("int");

                    b.Property<double>("MaxPowerTubeC")
                        .HasColumnType("float");

                    b.Property<double>("MaxPowerWatts")
                        .HasColumnType("float");

                    b.Property<int>("MinCurrentMa")
                        .HasColumnType("int");

                    b.Property<double>("MinSocPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "PeriodStart")
                        .IsUnique();

                    b.ToTable("BmsReadingHourly", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsReadingMinute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AlarmCount")
                        .HasColumnType("int");

                    b.Property<int>("AvgCurrentMa")
                        .HasColumnType("int");

                    b.Property<long>("AvgPackVoltageMv")
                        .HasColumnType("bigint");

                    b.Property<double>("AvgPowerWatts")
                        .HasColumnType("float");

                    b.Property<double>("AvgSocPercent")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("MaxBatteryTemp1C")
                        .HasColumnType("float");

                    b.Property<double>("MaxBatteryTemp2C")
                        .HasColumnType("float");

                    b.Property<int>("MaxCurrentMa")
                        .HasColumnType("int");

                    b.Property<int>("MaxDeltaCellMv")
                        .HasColumnType("int");

                    b.Property<double>("MaxPowerTubeC")
                        .HasColumnType("float");

                    b.Property<double>("MaxPowerWatts")
                        .HasColumnType("float");

                    b.Property<int>("MinCurrentMa")
                        .HasColumnType("int");

                    b.Property<double>("MinSocPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "PeriodStart")
                        .IsUnique();

                    b.ToTable("BmsReadingMinute", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BmsSite", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ImageMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CameraId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("int");

                    b.Property<string>("ImageType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("CameraId", "CapturedAt");

                    b.ToTable("ImageMetadata", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.PowerReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("BatteryCapacityKwh")
                        .HasColumnType("float");

                    b.Property<double?>("BatteryCurrentA")
                        .HasColumnType("float");

                    b.Property<double?>("BatteryPowerW")
                        .HasColumnType("float");

                    b.Property<double?>("BatteryStateOfChargePercent")
                        .HasColumnType("float");

                    b.Property<double?>("BatteryVoltageV")
                        .HasColumnType("float");

                    b.Property<string>("ChargerSourcePriority")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double?>("GridFrequencyHz")
                        .HasColumnType("float");

                    b.Property<double?>("GridPowerW")
                        .HasColumnType("float");

                    b.Property<double?>("GridVoltageV")
                        .HasColumnType("float");

                    b.Property<string>("InverterMode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("LoadPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("LoadPowerW")
                        .HasColumnType("float");

                    b.Property<double?>("OutputFrequencyHz")
                        .HasColumnType("float");

                    b.Property<string>("OutputSourcePriority")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("OutputVoltageV")
                        .HasColumnType("float");

                    b.Property<double?>("PvPowerW")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double?>("SystemPowerW")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("SourceId", "RecordedAt")
                        .IsUnique();

                    b.HasIndex("SourceSystem", "RecordedAt");

                    b.ToTable("PowerReading", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.PowerConfigurationSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CommandCapabilityCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SettingCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("SourceId", "PayloadHash")
                        .IsUnique();

                    b.HasIndex("SourceId", "RecordedAt")
                        .IsUnique();

                    b.ToTable("PowerConfigurationSnapshot", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.PowerDeviceInventorySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MqttEntityCount")
                        .HasColumnType("int");

                    b.Property<int>("MqttStateTopicCount")
                        .HasColumnType("int");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestMetricCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("SourceId", "PayloadHash")
                        .IsUnique();

                    b.HasIndex("SourceId", "RecordedAt")
                        .IsUnique();

                    b.ToTable("PowerDeviceInventorySnapshot", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.SiteConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Key");

                    b.ToTable("SiteConfiguration", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.WeatherHourly", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AvgBarometricPressureInHg")
                        .HasColumnType("float");

                    b.Property<double?>("AvgDewPointF")
                        .HasColumnType("float");

                    b.Property<double?>("AvgHumidityPercent")
                        .HasColumnType("float");

                    b.Property<double?>("AvgSolarRadiationWm2")
                        .HasColumnType("float");

                    b.Property<double?>("AvgTemperatureF")
                        .HasColumnType("float");

                    b.Property<double?>("AvgWindSpeedMph")
                        .HasColumnType("float");

                    b.Property<int?>("DominantWindDirectionDegrees")
                        .HasColumnType("int");

                    b.Property<double?>("MaxTemperatureF")
                        .HasColumnType("float");

                    b.Property<double?>("MaxUvIndex")
                        .HasColumnType("float");

                    b.Property<double?>("MaxWindGustMph")
                        .HasColumnType("float");

                    b.Property<double?>("MinTemperatureF")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("TotalRainfallInches")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart")
                        .IsUnique();

                    b.HasIndex("StationId", "PeriodStart");

                    b.ToTable("WeatherHourly", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.WeatherMinute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AvgBarometricPressureInHg")
                        .HasColumnType("float");

                    b.Property<double?>("AvgDewPointF")
                        .HasColumnType("float");

                    b.Property<double?>("AvgHumidityPercent")
                        .HasColumnType("float");

                    b.Property<double?>("AvgSolarRadiationWm2")
                        .HasColumnType("float");

                    b.Property<double?>("AvgTemperatureF")
                        .HasColumnType("float");

                    b.Property<double?>("AvgWindSpeedMph")
                        .HasColumnType("float");

                    b.Property<int?>("DominantWindDirectionDegrees")
                        .HasColumnType("int");

                    b.Property<double?>("MaxUvIndex")
                        .HasColumnType("float");

                    b.Property<double?>("MaxWindGustMph")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("TotalRainfallInches")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart")
                        .IsUnique();

                    b.HasIndex("StationId", "PeriodStart");

                    b.ToTable("WeatherMinute", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.WeatherRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("BarometricPressureInHg")
                        .HasColumnType("float");

                    b.Property<double?>("DewPointF")
                        .HasColumnType("float");

                    b.Property<double?>("HumidityPercent")
                        .HasColumnType("float");

                    b.Property<double?>("RainfallInches")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SolarRadiationWm2")
                        .HasColumnType("float");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("TemperatureF")
                        .HasColumnType("float");

                    b.Property<double?>("UvIndex")
                        .HasColumnType("float");

                    b.Property<int?>("WindDirectionDegrees")
                        .HasColumnType("int");

                    b.Property<double?>("WindGustMph")
                        .HasColumnType("float");

                    b.Property<double?>("WindSpeedMph")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("StationId", "RecordedAt")
                        .IsUnique()
                        .HasFilter("[StationId] IS NOT NULL");

                    b.ToTable("WeatherRaw", "v9");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ApiKey", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.ApiKeyOwner", "Owner")
                        .WithMany("ApiKeys")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ApiKeyClaim", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.ApiKey", "ApiKey")
                        .WithMany("Claims")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsAlarm", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsDevice", "Device")
                        .WithMany("Alarms")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsCellResistance", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsReading", "Reading")
                        .WithMany("CellResistances")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsCellVoltage", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsReading", "Reading")
                        .WithMany("CellVoltages")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsDevice", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsSite", "Site")
                        .WithMany("Devices")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsDeviceConfig", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsDevice", "Device")
                        .WithMany("Configs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsDeviceInfo", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsDevice", "Device")
                        .WithMany("DeviceInfos")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsReading", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsDevice", "Device")
                        .WithMany("Readings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsReadingHourly", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsReadingMinute", b =>
                {
                    b.HasOne("HVO.DataModels.Models.V9.BmsDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ApiKey", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.ApiKeyOwner", b =>
                {
                    b.Navigation("ApiKeys");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsDevice", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Configs");

                    b.Navigation("DeviceInfos");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsReading", b =>
                {
                    b.Navigation("CellResistances");

                    b.Navigation("CellVoltages");
                });

            modelBuilder.Entity("HVO.DataModels.Models.V9.BmsSite", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
